plot:
  width: 125
  length: 60
  extra_space: 5
structures:
  polygons:
    - name: House
      points:
        - [11, 22]
        - [11, 63]
        - [49, 63]
        - [49, 28]
        - [37, 28]
        - [37, 22]
        - [11, 22]
      edgecolor: red
      linewidth: 1.5
      zorder: 3
    - name: Patio
      points:
        - [32.5, 63]
        - [19.5, 63]
        - [19.5, 73.5]
        - [32.5, 73.5]
      edgecolor: purple
      linewidth: 1.5
      zorder: 2
    - name: Driveway
      points:
        - [12, 0]
        - [29, 0]
        - [29, 15]
        - [35, 15]
        - [35, 22]
        - [12, 22]
        - [12, 0]
      edgecolor: purple
      linewidth: 1.5
      zorder: 2
    - name: Garden Bed Model 2
      points:
        - [46, 73.5]
        - [46, 79.5]
        - [49, 79.5]
        - [49, 73.5]
      edgecolor: green
      linewidth: 1.5
      zorder: 2
      needs_irrigation: True
    - name: Tulip Bed
      points:
        - [1, 115]
        - [26, 115]
        - [26, 124]
        - [1, 124]
        - [1, 115]
      edgecolor: green
      linewidth: 1.5
      zorder: 2
      needs_irrigation: True
    - name: Porch Plants
      points:
        - [37.5, 22]
        - [49, 22]
        - [49, 27.5]
        - [37.5, 27.5]
        - [37.5, 22]
      edgecolor: green
      linewidth: 1.5
      zorder: 2
      needs_irrigation: True
  shaped_structures:
    - name: Garden Bed Model 1
      shape: rectangle
      alignment: center
      positions:
        - {x: 10, y: 105}
        - {x: 22, y: 105}
        - {x: 34, y: 105}
        - {x: 46, y: 105}
      dimensions:
        length: 8
        breadth: 4
      edgecolor: green
      linewidth: 1.5
      zorder: 4
      needs_irrigation: True
    - name: Garden Bed Model 2
      shape: rectangle
      alignment: center
      positions:
        - {x: 6, y: 112.5}
        - {x: 12, y: 112.5}
        - {x: 18, y: 112.5}
        - {x: 24, y: 112.5}
        - {x: 30, y: 112.5}
        - {x: 36, y: 112.5}
        - {x: 42, y: 112.5}
        - {x: 48, y: 112.5}
      dimensions:
        length: 6
        breadth: 3
      edgecolor: green
      linewidth: 1.5
      zorder: 4
      needs_irrigation: True
    - name: Garden Bed Model 3
      shape: rectangle
      alignment: center
      positions:
        - {x: 39, y: 116.5}
        - {x: 39, y: 121.5}
      dimensions:
        length: 24
        breadth: 3
      edgecolor: green
      linewidth: 1.5
      zorder: 4
      needs_irrigation: True
    - name: Tree
      shape: circle
      alignment: center
      positions:
        - {x: 45, y: 7.5}
      dimensions:
        radius: 2.5
      edgecolor: green
      linewidth: 1.5
      zorder: 4
      needs_irrigation: True
irrigation:
  lines:
    - name: Main Line A
      coordinates:
        - [0, 10]
        - [15, 10]
        - [15, 20]
        - [30, 20]
      color: magenta
      linewidth: 2.0

  fittings:
    - name: Elbow near Bed #1
      fitting_type: elbow
      position: [15, 10]   # The 90° turn
      color: lime

    - name: 3-Way Split near Bed #2
      fitting_type: tee
      position: [30, 20]
      color: lime

    - name: End Cap near Bed #1
      fitting_type: end_cap
      position: [15, 20]
      color: lime