plot:
  width: 125
  length: 60
  extra_space: 5

structures:
  polygons:
    - name: House
      points:
        - [11, 22]
        - [11, 63]
        - [49, 63]
        - [49, 28]
        - [37, 28]
        - [37, 22]
        - [11, 22]
      edgecolor: red
      linewidth: 1.5
      zorder: 3

    - name: Patio
      points:
        - [32.5, 63]
        - [19.5, 63]
        - [19.5, 73.5]
        - [32.5, 73.5]
      edgecolor: purple
      linewidth: 1.5
      zorder: 2

    - name: Driveway
      points:
        - [12, 0]
        - [29, 0]
        - [29, 15]
        - [35, 15]
        - [35, 22]
        - [12, 22]
        - [12, 0]
      edgecolor: purple
      linewidth: 1.5
      zorder: 2

    - name: Garden Bed Model 2
      points:
        - [46, 73.5]
        - [46, 79.5]
        - [49, 79.5]
        - [49, 73.5]
      edgecolor: green
      linewidth: 1.5
      zorder: 2
      needs_irrigation: True
      main_line_alignment: "bottom"
      number_of_drip_lines: 2
      main_line_inlet: right

    - name: Tulip Bed
      points:
        - [1, 115]
        - [26, 115]
        - [26, 124]
        - [1, 124]
        - [1, 115]
      edgecolor: green
      linewidth: 1.5
      zorder: 2
      needs_irrigation: True
      main_line_alignment: "right"
      number_of_drip_lines: 4
      main_line_inlet: bottom 
    - name: Porch Plants
      points:
        - [37.5, 22]
        - [49, 22]
        - [49, 27.5]
        - [37.5, 27.5]
        - [37.5, 22]
      edgecolor: green
      linewidth: 1.5
      zorder: 2
      needs_irrigation: True
      number_of_drip_lines: 3
      main_line_alignment: "right"

  shaped_structures:
    - name: Garden Bed Model 1
      shape: rectangle
      alignment: center
      dimensions:
        length: 8
        breadth: 4
      edgecolor: green
      linewidth: 1.5
      zorder: 4
      # Default irrigation for these four positions
      needs_irrigation: True
      main_line_alignment: "optimal"
      number_of_drip_lines: 2
      positions:
        - { x: 10, y: 105, name: "Bed A", main_line_alignment: "right", main_line_inlet: bottom}
        - { x: 22, y: 105, name: "Bed B", main_line_alignment: "left" , main_line_inlet: bottom}
        - { x: 34, y: 105, name: "Bed C", main_line_alignment: "right" , main_line_inlet: bottom}
        - { x: 46, y: 105, name: "Bed D", main_line_alignment: "left" , main_line_inlet: bottom}

    - name: Garden Bed Model 2
      shape: rectangle
      alignment: center
      dimensions:
        length: 6
        breadth: 3
      edgecolor: green
      linewidth: 1.5
      zorder: 4
      needs_irrigation: True
      main_line_alignment: "optimal"
      number_of_drip_lines: 2
      positions:
        - { x: 6, y: 112.5, name: "Bed E", main_line_alignment: "right", main_line_inlet: top }
        - { x: 12, y: 112.5, name: "Bed F", main_line_alignment: "left" , main_line_inlet: top }
        - { x: 18, y: 112.5, name: "Bed G", main_line_alignment: "right" , main_line_inlet: top }
        - { x: 24, y: 112.5, name: "Bed H", main_line_alignment: "left" , main_line_inlet: top }
        - { x: 30, y: 112.5, name: "Bed I", main_line_alignment: "right" , main_line_inlet: top }
        - { x: 36, y: 112.5, name: "Bed J", main_line_alignment: "left" , main_line_inlet: top }
        - { x: 42, y: 112.5, name: "Bed K", main_line_alignment: "right" , main_line_inlet: top }
        - { x: 48, y: 112.5, name: "Bed L", main_line_alignment: "left", main_line_inlet: top  }  # disable irrigation

    - name: Garden Bed Model 3
      shape: rectangle
      alignment: center
      dimensions:
        length: 24
        breadth: 3
      edgecolor: green
      linewidth: 1.5
      zorder: 4
      needs_irrigation: True
      main_line_alignment: "optimal"
      number_of_drip_lines: 1
      positions:
        - { x: 39, y: 116.5, name: "Bed M", main_line_alignment: "left", main_line_inlet: bottom  }
        - { x: 39, y: 121.5, name: "Bed N", main_line_alignment: "left", main_line_inlet: bottom  }

    - name: Tree
      shape: circle
      alignment: center
      dimensions:
        radius: 2.5
      edgecolor: green
      linewidth: 1.5
      zorder: 4
      needs_irrigation: True
      positions:
        - { x: 45, y: 7.5, name: "Tree 1", number_of_drip_lines: 1 }
      main_line_inlet: right

irrigation:
  lines:
    - name: Main Line A
      coordinates:
        - [0, 10]
        - [15, 10]
        - [15, 20]
        - [30, 20]
      color: magenta
      linewidth: 2.0

  fittings:
    - name: Elbow near Bed #1
      fitting_type: elbow
      position: [15, 10]
      color: lime

    - name: 3-Way Split near Bed #2
      fitting_type: tee
      position: [30, 20]
      color: lime

    - name: End Cap near Bed #1
      fitting_type: end_cap
      position: [15, 20]
      color: lime
